package com.moviebooking.dto;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Response DTO returned after checkout is created.
 */
public class CheckoutResponse
{
    /** User Id associated with the checkout. */
    private String userId;

    /** Showtime Id associated with the checkout. */
    private String showtimeId;

    /** Checkout Id generated by the backend. */
    private String checkoutId;

    /** Seats associated with the checkout. */
    private List<String> seatLabels;

    /** Checkout total.*/
    private BigDecimal total;

    /** Timestamp of created checkout. */
    private LocalDateTime createdAt;

    /** Current checkout status. */
    private String status;

    /**
     * Constructs a checkout response.
     * @param checkoutId generated checkout Id.
     * @param userId The user Id.
     * @param showtimeId The showtime Id.
     * @param seatLabels selected seats.
     * @param total Checkout total.
     * @param status Checkout status.
     * @param createdAt Creation timestamp.
     */
    public CheckoutResponse(long checkoutId, long userId, long showtimeId, List<String> seatLabels, BigDecimal total, String status, LocalDateTime createdAt)
    {
        this.checkoutId = Long.toUnsignedString(checkoutId);
        this.userId = Long.toUnsignedString(userId);
        this.showtimeId = Long.toUnsignedString(showtimeId);
        this.seatLabels = seatLabels;
        this.total = total;
        this.status = status;
        this.createdAt = createdAt;
    }//end of checkoutresponse()

    /** @return checkout Id. */
    public String getCheckoutId() {return checkoutId;}

    /** @return User Id */
    public String getUserId() {return userId;}

    /** @return showtime id */
    public String getShowtimeId() {return showtimeId;}

    /** @return seat labels */
    public List<String> getSeatLabels() {return seatLabels;}

    /** @return checkout status */
    public String getStatus() {return status;}

    /** @return  total*/
    public BigDecimal getTotal() {return total;}

    /** @return createdAt timestamp*/
    public LocalDateTime getCreatedAt() {return createdAt;}
}//end of checkoutresponse class